### ISSUE TITLE
Add support for Webkit / Remove dash glyph names

### ISSUE THREAD

**Issue by askmatey** [fxos-components/fxos-icons#25]
While porting my firefox-os application to `cordova`, I have recognized that glyph names with a dash `-` (like `alarm-stop`, `seek-up` etc) are not recognized by Webkit.

**You can be sure**, I am not a fan of the Webkit engine. However, I'm pretty sure the bug could be closed, by providing a separate version of glyph names without dashes `-`.

**Comment by wilsonpage** [comment]
You're right, we do need to fix this. Do you think simply removing all hyphens is the best approach?

`data-icon="foo-bar"` => `data-icon="foobar"`

**Comment by askmatey** [comment]
Yes, removing the dashes is the solution.

I have forked this repository locally, renamed all files manually and used the grunt task `grunt default`.

Works bloody good now.

**Comment by wilsonpage** [comment]
Can you submit a pull-request back to this repo?

**Comment by askmatey** [comment]
With all the renamed icons ?

The data-icon syntax will be different from then.

**Comment by wilsonpage** [comment]
Yes please :)

**Comment by wilsonpage** [comment]
Any update on this?
