### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by moimael** [fxos-components/fxos-icons#45]
Hi,

It would be great to be able to download this project from npm. I use browserify and do not want to use bower only for icons.

Thanks !

**Comment by wilsonpage** [comment]
Do we have any suggestions on how we might load `.css` from within `gaia-icons.js`? With Bower we can make an assuming about what the path to `gaia-icons.css` will be (`/bower_components/gaia-icons/gaia-icons.css`).

With NPM the path could be much deeper, and all depends on the context of gaia-icons in an application's dependency tree. (eg `node_modules/gaia-header/node_modules/gaia-icons/gaia-icons.css` or `node_modules/gaia-icons/gaia-icons.css`, ...).

+@jedireza

**Comment by wilsonpage** [comment]
I think some build tools cope with this issue by inlining small assets into the final bundle.

**Comment by jedireza** [comment]
> Do we have any suggestions on how we might load `.css` from within `gaia-icons.js`? With bower we can make an assumption about what the path to `gaia-icons.css` will be (`/bower_components/gaia-icons/gaia-icons.css`).

There is logic to control the base path in [`gaia-icons.js`](https://github.com/gaia-components/gaia-icons/blob/219f532cc4cb192006de3b175597e080787adbe5/gaia-icons.js#L8-L10):

```js
var base = window.GAIA_ICONS_BASE_URL ||
           window.COMPONENTS_BASE_URL ||
           'bower_components/';
```

I too don't want to use bower and prefer simply using npm + a bundle tool (browserify/webpack). I also don't like how this script makes assumptions about how I want to uses these assets (global pollution). So I wouldn't use this script (`gaia-icons.js`). That doesn't mean it shouldn't exist for someone who wants that classic no-build-web-page, I just wouldn't `require('gaia-icons')` in my code.

I'd like downloaded the content of any `gaia-components` via npm (into `/node_modules/gaia-icons/`) and then in my own build scripts I'd copy, concatenate or use the files I want to consume manually. This is the same way I'm consuming Bootstrap and Font-Awesome for example.

> With NPM the path could be much deeper, and all depends on the context of gaia-icons in an application's dependency tree. (eg /node_modules/gaia-header/node_modules/gaia-icons/gaia-icons.css or /node_modules/gaia-icons/gaia-icons.css, ...).

This is an anti-pattern I've mentioned before. It's nice that bower flattens dependencies. I believe they do for people who actually publish the `/bower_components` directory and don't want lots of duplication on disk.

If I my app depends on `ModuleA` and `ModuleA` depends on `ModuleB`, my app shouldn't be using `ModuleB` directly. If my app also depends on `ModuleB` it should be defined explicitly in the `<package-manager>.json`. And in the case of bower (and npm in the future), these dependencies would get flattened and the footprint on disk would be the same. But the dependency would be clear as day.

**Comment by wilsonpage** [comment]
@jedireza is there a smarter way we can support the `require('gaia-icons')` workflow?

**Comment by jedireza** [comment]
> is there a smarter way we can support the require('gaia-icons') workflow?

I'm not sure there's anything to change here. `gaia-icons` as a module is a way to distribute versioned assets and in the case of `gaia-icons.js` a browser script to use if you're not bundling assets yourself.

I don't see why we'd `require('gaia-icons')`. What would I do with that in my script?

```js
var gaiaIcons = require('gaia-icons');

console.log(gaiaIcons.loaded);
// false

// ... after the network request finishes, which I can't detect or listen for ...

console.log(gaiaIcons.loaded);
// true
```

I don't imagine myself using that `loaded` boolean, the assets of the module are what I'm after.

Keep in mind publishing to and installing with npm doesn't always imply that we'll be calling `require` for that module.

**Comment by wilsonpage** [comment]
Some components (like gaia-header), have a hard dependency on `gaia-icons.css` so we need a way to load them when someone uses `gaia-header.js` in there app. `gaia-icons.js` seems like the best way to do this without the user having to be aware of sub-dependencies.

If we depended on `gaia-icons.css` the usual UX would look like this:

1. User bower/npm installs gaia-header
2. They add `gaia-header.js` to their app
3. They notice icons are missing
4. The poke around and eventually realise there is a `.css` dependency
5. They add `some/path/gaia-icons.css` to their document
6. The component finally works

I don't want that experience :(

**Comment by wilsonpage** [comment]
`gaia.icons.js` is basically a loader script that makes sure `gaia-icons.css` is never loaded twice.

**Comment by jedireza** [comment]
Or we could document the dependency in the `gaia-header` readme with instructions on how to access the asset files. This should help eliminate the process-of-elimination experience you described.

I'm noticing that most `gaia-components` are designed and distributed with tight coupling to bower and with come with somewhat-strict assumptions about how they should be used. If we don't consider different use cases and plan for more generic consumption, I can imagine people just not using them or creating their own alternatives. Which would be a shame since a lot of work has already been done and helps the continuity of Gaia apps.

I believe we can support both. It shouldn't be a one or the other situation. And currently it's a bower only world.

**Comment by moimael** [comment]
Any progress on this ? :)

**Comment by wilsonpage** [comment]
Done.

```bash
npm install fxos-icons
```
