### ISSUE TITLE
Icons are not centered correctly in Chromium

### ISSUE THREAD

**Issue by Rudloff** [fxos-components/fxos-icons#46]
When icons are used with `text-align: center`, they are not centered correctly in Chromium.

Chromium:
![Chromium](https://cloud.githubusercontent.com/assets/840125/9454976/f6879bac-4ac6-11e5-81b5-a5bf22e5d0ab.png)

Firefox:
![Firefox](https://cloud.githubusercontent.com/assets/840125/9454978/fbe0a652-4ac6-11e5-9e49-f9ce41c65dc4.png)

**Comment by wilsonpage** [comment]
Does this affect all icons? Can you try icons without a `-` in the name?

**Comment by Rudloff** [comment]
You're right, it only affects icons with a - in the name.

**Comment by wilsonpage** [comment]
Interesting. Blink seems to have issues here. We could rename all icons to remove the `-`. But that would take some time to migrate the dependent apps. @gmarty any thoughts on this?

**Comment by gmarty** [comment]
It really looks like a bug in Blink. I remember it having issues in the past with icon name containing a `-`.
My recommendation would be to fill a bug.
Is there a similar bug in webkit?

**Comment by Rudloff** [comment]
I can reproduce with Safari too.
