### ISSUE TITLE
link in description of fxos-components/fxos-icons is a 404

### ISSUE THREAD

**Issue by anaran** [fxos-components/fxos-icons#62]
See these links:

http://gaia-components.github.io/gaia-icons/

  referenced from

https://github.com/fxos-components/fxos-icons

Details:

 Icon font used throughout Firefox OS (Gaia) http://gaia-components.github.io/gaia-icons/

http://mzl.la/1vxCDgA

**Comment by wilsonpage** [comment]
Appears fixed now, thanks! :)
